### ISSUE TITLE
Error enabling production mode

### ISSUE THREAD

**Issue by kennethdekker** [magento-engcom/php-7.2-support#126]
I'm facing an issue when enabling the production modus through CLI. Error: The value you set has already been locked. To change the value, use the --lock-env option.

Command: php bin/magento deploy:mode:set production -f

Any idea?

**Comment by buskamuza** [comment]
@kennethdekker , do you have it on PHP 7.2 only? And do you have full stack trace?

**Comment by buskamuza** [comment]
Closing as no feedback for a few months.
