### ISSUE TITLE
Broken unit tests

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#13]
See https://travis-ci.org/magento-engcom/php-7.2-support/jobs/342577316

See issues in the epic.

Other tests will be fixed in the scope of:
- #10
- #7
- #4 (requires Symfony upgrade to a major version, which causes tests failure due to removed Symfony classes)
- #9

**Comment by buskamuza** [comment]
Related issues:
* https://github.com/magento-engcom/php-7.2-support/issues/7
* https://github.com/magento-engcom/php-7.2-support/issues/8

**Comment by giabmf11** [comment]
All tests are passing. Is this still valid?

**Comment by buskamuza** [comment]
Updated the description

**Comment by buskamuza** [comment]
* run unit tests locally with `--ignore-platfotm-reqs` for `composer install`
* validate on a `workaround`-based branch on Travis CI
