### ISSUE TITLE
Update PHP version dependency to ~7.2.0

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#15]
Update `composer.json` to add PHP ~7.2.0:
* root `composer.json` and `composer.lock`
* module's and frameworks' `composer.json` - remove PHP requirement (ex: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/AdminNotification/composer.json#L5)
* `dev/tests/functional/composer.json`

AC:
- use `require-dev` section, so Magento doesn't claim PHP 7.2 support until it's fully implemented and verified
- existing tests (on PHP 7.1) are green

**Comment by pmclain** [comment]
@buskamuza I can take this one.

**Comment by buskamuza** [comment]
@pmclain , I've added you to the project and assigned the task.

**Comment by buskamuza** [comment]
To be done in #86
