### ISSUE TITLE
Broken static tests

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#16]
See https://travis-ci.org/magento-engcom/php-7.2-support/jobs/342577318

The tests should be fixed in the scope of:
- #15
- #7

**Comment by buskamuza** [comment]
Issues:
* https://github.com/magento-engcom/php-7.2-support/issues/7
* https://github.com/magento-engcom/php-7.2-support/issues/15

**Comment by giabmf11** [comment]
The tests referenced above are all passing. Is this still valid?

**Comment by buskamuza** [comment]
Updated the description
