### ISSUE TITLE
magento/composer does not support PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#2]
Update https://github.com/magento/composer, so it supports PHP 7.2

Repo: https://github.com/magento-engcom/magento-composer-php-7.2-support

AC:
- https://github.com/magento-engcom/magento-composer-php-7.2-support/blob/engcom-master/composer.json#L11 includes `~7.2.0`
- Setup scenarios pass on PHP 7.2 installation

Scenarios:
- Web Setup Wizard: list, update, install an extension
- Web Setup Wizard: upgrade Magento application to the next version
- Magento CLI `setup:install`
- Magento CLI `setup:upgrade`
- Magento CLI `module:enable`
- Magento CLI `module:disable`
- Cloud setup/deployment

**Comment by giabmf11** [comment]
Composer supports PHP 7.2. Does this issue address Magento's Composer implementation does not support PHP 7.2? The issue needs a better description because I don't understand the work that needs to be done. I also don't understand where the incompatibilities reside.

**Comment by buskamuza** [comment]
@piotrekkaminski , please review test scenarios and add more scenarios if necessary.

**Comment by buskamuza** [comment]
@giabmf11 , https://github.com/magento/composer/blob/master/composer.json#L11 doesn't include PHP 7.2 in the list of supported versions. So it should be added and validated that it's really supported. I updated the description.

**Comment by piotrekkaminski** [comment]
what about removing an extension? is it supported? 
what about manual composer commands
cloud setup/deployment needs to be tested as a scenario

**Comment by buskamuza** [comment]
@piotrekkaminski, why removing? It's our extension, used in Web Setup Wizard. Magento supports it.
What do you mean under "manual composer commands"? It can't affect Composer itself. But it can affect our CLI commands that use Composer via library.
You're right - cloud should be tested. I'll add it here.

**Comment by buskamuza** [comment]
I'm working on merging https://github.com/magento-engcom/magento-composer-php-7.2-support/pull/1
When it's done, Magento repo can be updated with the new version dependency.

Regarding validation of use cases, there were no changes in the code (only in tests), so it should not cause any issues on currently supported versions of PHP, so there is no point in testing now. I propose to go through important scenarios when Magento will be at least installable on PHP 7.2. I'll create a test suite and add scenarios from this ticket there.

**Comment by buskamuza** [comment]
`composer/composer` should be also updated in the scope of this task (or it will be incompatible with the updated version of `magento/composer`)

**Comment by buskamuza** [comment]
https://github.com/magento-engcom/magento-composer-php-7.2-support/pull/1 is merged.
Please proceed with updating Magento `composer.json`.
Please use the branch https://github.com/magento/composer/tree/1.3.0 . Later, when PHP 7.2 work will be done and be ready for merging to mainline, we'll release the tag and will be able to reference it as a normal version.
