### ISSUE TITLE
magento/zf1 does not support PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#22]
Update https://github.com/magento/zf1, so it supports PHP 7.2.
* review ZF1 library for incompatibilities with PHP 7.2
  
Repo: https://github.com/magento-engcom/zf1-php-7.2-support

**Comment by buskamuza** [comment]
One of the issues - https://github.com/magento-architects/zf1/commit/2185777a4a374d954121e74738ff1325b5ef3f9d

**Comment by buskamuza** [comment]
- separate project
- separate ZF1 modules into:
   - possible to upgrade to ZF2 and upgrade them
      - remove those items from ZF1. Check Marketplace before removal
   - impossible to upgrade to ZF2. Fix those

**Comment by okorshenko** [comment]
Just FYI: https://github.com/magento/magento2/pull/9347
