### ISSUE TITLE
3rd-party libraries do not support PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#24]
# List of Libraries to Update

* [zendframework/zend-mail](https://github.com/zendframework/zend-mail) - update to ver. 2.9.0. Issue #12
* [zend-soap](https://github.com/zendframework/zend-soap) - ver. 2.7.0 supports PHP 7.2. Issue #37 to validate usage of the new version.
* ~~[pdepend/pdepend](https://github.com/pdepend/pdepend) - uses deprecated `$php_errormsg` parameter~~ - used for PHP < 5.3
* ~~[squizlabs/php_codesniffer](https://github.com/squizlabs/PHP_CodeSniffer) - uses deprecated `$php_errormsg` parameter~~ - it's in the tests, not used in the executable
* [friendsofphp/php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) - ver. 2.10.0 supports 7.2. Covered in #86
* [done] [pelago/emogrifier](https://github.com/MyIntervals/emogrifier) - ver. 2.0.0 supports 7.2. Issue #3 to validate.
* [done] [colinmollenhour/php-redis-session-abstract](https://github.com/colinmollenhour/php-redis-session-abstract) - ver. 1.3.8 supports PHP 7.2. Issue #1 to validate.
* [done] [sjparkinson/static-review](https://packagist.org/packages/sjparkinson/static-review) - remove. #40
* [colinmollenhour/cache-backend-file](https://packagist.org/packages/colinmollenhour/cache-backend-file) - update tp ver. 1.4.1. Issue #88

Solution:
* Create PRs to the libs that still have issues. Wait for them being merged and new version released. Depend on the new version.
* Update dependencies to new versions that support PHP 7.2 (see versions mentioned in the list above)

# Acceptance Criteria

* `composer update` passes

In scope of this task, update `composer.json` and `composer.lock`, so that `composer install` passes. Any issues in the code to be reviewed and solved in related tasks for each library.

**Use this branch for PRs** - https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade

# Related Issues

* https://github.com/magento-engcom/php-7.2-support/issues/22
* https://github.com/magento-engcom/php-7.2-support/issues/2

**Comment by buskamuza** [comment]
https://github.com/colinmollenhour/php-redis-session-abstract/issues/22

**Comment by joshuaadickerson** [comment]
Zend-mail issue already created for 7.2 support: https://github.com/zendframework/zend-mail/issues/177

**Comment by buskamuza** [comment]
From today's meeting:
- move PHP 7.2 to "require" section
- drop PHP 7.0
   - ensure no internal builds are running on PHP 7.0
   - requires https://app.zenhub.com/workspace/o/magento-engcom/php-7.2-support/issues/25
- updated to latest versions of libs

**Comment by RomaSlobodeniuk** [comment]
Hi, right from "event-chernivtsi-cd" I've found several places incompatible with php7.2, the first is `vendor/colinmollenhour/cache-backend-file/File.php:81` uses "each()" function. Also magento uses the last version of this library (1.4): 
![ca55aed139](https://user-images.githubusercontent.com/20392418/36341820-bc74c67c-13fc-11e8-9e9f-1af6f772a9a3.jpg)

**Comment by RomaSlobodeniuk** [comment]
`/vendor/magento/zendframework1/library/Zend/Cache/Backend.php:79` - here's a similar problem related to deprecated function "each()".

**Comment by pmclain** [comment]
Regarding `colinmollenhour/cache-backend-file`: There are two commits in the source repository removing the `each` method calls: 
https://github.com/colinmollenhour/Cm_Cache_Backend_File/commit/e8d1e3800b00c5f23ef89a925dce7daf580c972c  
https://github.com/colinmollenhour/Cm_Cache_Backend_File/commit/161f8caef717fb29538b44ad2dd50b8715f52f6b  

I commented on https://github.com/colinmollenhour/Cm_Cache_Backend_File/issues/26 asking about tagging a release including those commits. I'd prefer that over referencing a commit in `composer.json`

**Comment by Ocramius** [comment]
@buskamuza `zend-mail` got a `2.9.0` release with PHP 7.2 compat.
