### ISSUE TITLE
Environment with PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#27]
Create a Docker box with PHP 7.2 for manual testing and development.

Host:
- Mac
- Linux
- Win

- xDebug

**Comment by joshuaadickerson** [comment]
I'd recommend Docker instead of Vagrant.

**Comment by buskamuza** [comment]
Look at https://github.com/meanbee/docker-magento2/pull/121

**Comment by giabmf11** [comment]
I agree with Josh. We should stop promoting Vagrant and move to Docker because it's more stable and doesn't have file replication or security issues.

**Comment by vrann** [comment]
Docker Image which can be takes as a base for PHP 7.2 https://github.com/magento/magento2devbox-web

**Comment by giabmf11** [comment]
The image and instructions on how to install the environment are here: https://hub.docker.com/r/giabmf11/php72-upgrade/

Please take a look, follow the instructions and let me know if anything is missing.

**Comment by buskamuza** [comment]
1. `docker-compose.yml` requires formatting. Maybe it's better to put it on the GitHub and provide the link on the docker hub?
2. Please add link to the docker image at the project wiki https://github.com/magento-engcom/php-7.2-support/wiki
