### ISSUE TITLE
pelago/emogrifier does not support PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#3]
Update pelago/emogrifier (https://github.com/MyIntervals/emogrifier)  to the version that supports PHP 7.2.

AC:
* tests are green
* usage scenarios are working

Ver. 2.0.0 supports 7.2

**Comment by buskamuza** [comment]
Closed in favor of https://github.com/magento-engcom/php-7.2-support/issues/24

**Comment by pmclain** [comment]
@buskamuza Looks like this has already been done https://github.com/magento-engcom/php-7.2-support/blob/7ce6ffbcf3fc823f0782b32a462c16b7fe42c5fc/composer.lock#L958

**Comment by ihor-sviziev** [comment]
It was fixed in https://github.com/magento/magento2/pull/13351. I think we can close this task
