### ISSUE TITLE
friendsofphp/php-cs-fixer does not support PHP 7.2

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#4]
Update friendsofphp/php-cs-fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer) to the version that supports PHP 7.2. Install latest version of friendsofphp/php-cs-fixer

AC:
* tests are green
* usage scenarios are working

It also requires update of `symfony/console`, `symfony/process` and `symfony/event-dispatcher` to a newer versions. Please update to the latest possible.

**Comment by buskamuza** [comment]
Closed in favor of https://github.com/magento-engcom/php-7.2-support/issues/24

**Comment by pmclain** [comment]
As previously mentioned this will require an update of `symfony/console` to at least `v3.2.0`. `symfony/console` is currently restricted to `~2.3, !=2.7.0` by:
* `magento/magento2ce`
* `magento/composer`
* `sjparkinson/static-review` (abandoned)

**Comment by okorshenko** [comment]
CC: @orlangur

**Comment by orlangur** [comment]
Yeah, people were complaining `symfony/console` update is blocked in another GitHub issues, I'm going to finish such removal in https://github.com/orlangur/magento2/commit/d38152fac8f9f5d486c7fe34873fa42afbca3cdb

**Comment by buskamuza** [comment]
Covered by #86
