### ISSUE TITLE
\Magento\Framework\Data\OptionSourceInterface::toOptionArray() implementations are incompatible with the interface

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#6]
Implementations of `\Magento\Framework\Data\OptionSourceInterface::toOptionArray()` are often incompatible with the interface and/or parent class, which causes fatal error in PHP 7.2.
Fix implementations so that interfaces are compatible.

**Note:** it's potentially backward incompatible change.

**Comment by YevSent** [comment]
@buskamuza, can you specify a build where I can find these errors? I've found that all arguments in `toOptionArray()` are optional and should not cause any errors.  It's not a good approach for children methods to have arguments different to interface specification but changes require deep refactoring.

Also, I didn't find any mentions about changed behavior for interface implementations.

**Comment by buskamuza** [comment]
I think those were internal builds. Can't find Travis logs with this error.
I reverted `e3285405a0242c23ae97741a149947cee16ccd1b` and ran internal builds again. This is what I got.

**Unit tests**
```
PHP Fatal error:  Declaration of Magento\Customer\Model\Customer\Attribute\Source\Website::getAllOptions() must be compatible with Magento\Eav\Model\Entity\Attribute\Source\Table::getAllOptions($withEmpty = true, $defaultValues = false) in /var/www/html/app/code/Magento/Customer/Model/Customer/Attribute/Source/Website.php on line 13
[Unit-Tests-CE] 
```

**Functional Tests > di:compile**
```
PHP Fatal error:  Declaration of Magento\Tax\Model\System\Config\Source\Tax\Country::toOptionArray($noEmpty = false) must be compatible with Magento\Directory\Model\Config\Source\Country::toOptionArray($isMultiselect = false, $foregroundCountries = '') in /var/www/html/app/code/Magento/Tax/Model/System/Config/Source/Tax/Country.php on line 8 [] []
```

**Web API tests**
```
PHP Fatal error:  Declaration of Magento\Customer\Model\ResourceModel\Address\Attribute\Source\Country::getAllOptions() must be compatible with Magento\Eav\Model\Entity\Attribute\Source\Table::getAllOptions($withEmpty = true, $defaultValues = false) in /var/www/html/app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/Country.php on line 21

PHP Fatal error:  Declaration of Magento\Customer\Model\Customer\Attribute\Source\Website::getAllOptions() must be compatible with Magento\Eav\Model\Entity\Attribute\Source\Table::getAllOptions($withEmpty = true, $defaultValues = false) in /var/www/html/app/code/Magento/Customer/Model/Customer/Attribute/Source/Website.php on line 62
```

Some of such cases may be not covered by tests I can run now, so all inheritance cases should be reviewed and fixed if implemented incorrectly.
