### ISSUE TITLE
Eliminate usage of Zend_Json from Magento 2 Open Source

### ISSUE THREAD

**Issue by vkublytskyi** [magento-engcom/php-7.2-support#69]
References count: 13
Used in EE/B2B: yes
 
Acceptance Criteria:
1. Usage of Zend_Json removed from Magento 2 Open Source
   - all references to Zend_Json are removed from Magento 2 Open Source
   - added static a test that verifies that Zend_Json is not used
   - Travis builds are green on PHP 7.1 environment
   - all backward incompatible changes are documented (if any)
   - if possible ZF1 component replaced by embedded PHP functionality or PSR interface otherwise migrated to ZF2
   - if ZF1 component replaced by ZF2 component:
     - there is an explanation why it is required to use external dependency
     - if usage of old ZF1 component was exposed in M2 interface/class signatures it is removed for new code
     - there is a list of PHP 7.2 compatibility issues of new ZF2 component
OR
2. There is an explanation why it is impossible to delete this dependency now:
   - described scope of work that is necessary to totally remove usage of Zend_Json
   - described what backward incompatible changes will be caused by dependency removal
   - listed what other ZF1 components are required for Zend_Json to support M2
     (if only limited functionality of Zend_Json is used by M2
     then not all dependencies may be required and some part of Zend_Json
     still may be removed if has incompatibility with PHP 7.2)
   - listed PHP 7.2 compatibility issues for Zend_Json

**Comment by bbatsche** [comment]
Zend_Json is too broadly used by code within the Magento Marketplace to eliminate entirely. It should not be a blocker for backwards compatibility with PHP 7.2 however.
