### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#7]
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

Warning on PHP 7.2: `Warning: count(): Parameter must be an array or an object that implements Countable`.
Usually, it's due to `null` being passed as an argument.
Also, usage of `sizeof()` should be fixed.

**Comment by kamilszarmach** [comment]
#distributed-cd
