### ISSUE TITLE
Warning: get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#9]
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

`Warning: get_class() expects parameter 1 to be object, null given` on PHP 7.2

**Comment by YevSent** [comment]
@buskamuza, could you clarify where exactly this warning appears? There are about 300 occurrences of `get_class()` usage in Magento code.

**Comment by centerax** [comment]
I cannot replicate, see here https://gist.github.com/centerax/6b6423d8913b6701e6bbfb6076f70d41

#distributed-cd

**Comment by centerax** [comment]
#distributed-cd
